// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $register from "./routes/register.tsx";
import * as $video_idvid_ from "./routes/video/[idvid].tsx";
import * as $videos from "./routes/videos.tsx";
import * as $Butonlogout from "./islands/Butonlogout.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $favbutton from "./islands/favbutton.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/register.tsx": $register,
    "./routes/video/[idvid].tsx": $video_idvid_,
    "./routes/videos.tsx": $videos,
  },
  islands: {
    "./islands/Butonlogout.tsx": $Butonlogout,
    "./islands/Counter.tsx": $Counter,
    "./islands/favbutton.tsx": $favbutton,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
